In [1]:
import pandas as pd
import numpy as np

In [3]:
info = pd.read_csv('../Dataset/childhood/dat/nonormalize.csv')

In [4]:
H_income = pd.read_csv('../Derivatives/childhood/H_income.csv')

In [5]:
# income median
merge = pd.merge(H_income, info, how='left', on='fsid').income_median_y
print(np.median(merge))
print(np.std(merge))
print(len(merge))

42500.0
69302.35575405444
128

In [8]:
H_child = pd.read_csv('../Derivatives/childhood/hurst.csv')

In [9]:
# age mean, std
print(H_child.age_scan.min())
print(H_child.age_scan.max())
print(H_child.age_scan.mean())
print(H_child.age_scan.std())
print(H_child.male.sum()/H_child.shape[0])

4.011034
10.59011
6.551587507352939
1.3572760627845324
0.4632352941176471

In [17]:
ethnicity = pd.read_csv('../Dataset/childhood/dat/CBPD_data_DMD_2023.11.14.csv')

In [18]:
ethnicity['fsid'] ~

,record_id,my_first_instrument_complete.x,mackey_lab_questionnaire_timestamp,parent1,parent1_other_describe,dob,ethnicity,race_americanindian,race_asian,race_black,...,noscan_mock,noscan_metal,noscan_technical,noscan_unknown,cbcl_6yr_drink_d,cbcl_6yr_no_oth,video_permisions,cbcl_6yr_hobby,age_qs_setup,child_name
0,CBPD0001,2.0,NaN,1.0,NaN,NaN,0.0,0,1,0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,CBPD0002,2.0,NaN,2.0,NaN,NaN,0.0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CBPD0002_2,2.0,11/24/19 14:17,2.0,NaN,2012/11/10,0.0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CBPD0003,2.0,NaN,1.0,NaN,NaN,0.0,0,0,0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,CBPD0004,2.0,NaN,1.0,NaN,NaN,0.0,0,0,0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,CBPD0271,2.0,2007/08/23 11:25,1.0,NaN,9/14/17,0.0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,CBPD0272,2.0,7/23/23 11:26,1.0,NaN,3/17/15,0.0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,CBPD0273,2.0,2008/06/23 12:31,1.0,NaN,2007/10/16,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,CBPD0274,2.0,9/23/23 10:58,1.0,NaN,12/17/15,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,CBPD0275,2.0,9/23/23 13:00,2.0,NaN,4/14/17,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
H_child

,H_all1,H_all2,H_all3,H_all4,H_all5,H_all6,H_all7,H_all8,H_all9,H_all10,...,H_all400,record_id,age_scan,male,t1_rating_avg,parent_edu,income_median,fsid,age_square_scan,mean
0,1.055820,1.091977,1.112569,1.198315,1.134467,1.234834,1.212584,1.255547,1.192267,1.085781,...,1.233952,CBPD0002,6.672165,0.0,0.505512,0.363168,1.331310,sub-CBPD0002,0.105806,1.105021
1,1.175449,1.110350,1.101366,1.162866,1.114541,1.388172,1.151366,1.328838,1.260713,1.250951,...,1.311608,CBPD0007,4.599798,0.0,1.119947,1.475135,NaN,sub-CBPD0007,-1.185560,1.082829
2,1.379067,1.334777,1.310804,1.266850,1.380439,0.928590,1.245784,1.067453,0.952588,1.099009,...,1.281860,CBPD0012,5.106197,1.0,2.348816,-1.119455,-1.071133,sub-CBPD0012,-0.913844,1.202141
3,0.930987,0.941993,0.920347,1.097874,0.649279,0.873519,1.005722,0.985379,1.112896,0.922251,...,1.019314,CBPD0015,4.471116,1.0,0.505512,-1.119455,NaN,sub-CBPD0015,-1.250089,1.071798
4,1.215926,1.236878,1.076692,1.201762,1.222183,1.327828,1.240500,1.347517,1.276126,1.082176,...,1.331498,CBPD0020,7.370332,0.0,-0.723357,0.363168,-1.071133,sub-CBPD0020,0.647790,1.226890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,1.215436,1.145370,1.046563,1.098947,1.213554,1.198400,0.930879,1.280738,1.174345,1.172402,...,0.936908,CBPD0240,5.434631,1.0,-0.723357,-0.378144,-1.071133,sub-CBPD0240,-0.722460,1.180525
132,1.224764,1.313544,1.018373,1.212253,1.048438,1.220295,1.217048,1.270824,1.337021,1.259289,...,1.259886,CBPD0244,6.883098,0.0,-0.108923,-0.007488,1.331310,sub-CBPD0244,0.263870,1.229430
133,1.227294,1.166411,1.268998,1.359214,1.064336,1.043658,1.184233,1.175564,1.100940,1.216360,...,1.204621,CBPD0247,4.011034,0.0,-0.108923,-0.378144,1.331310,sub-CBPD0247,-1.465826,1.217041
134,1.180173,1.266522,1.084689,1.259570,1.295149,1.222433,1.177144,1.218466,1.219493,1.238048,...,1.198354,CBPD0252,7.830528,0.0,-0.723357,0.363168,NaN,sub-CBPD0252,1.034508,1.230939
135,1.308944,1.229487,1.307166,1.243996,1.249513,1.289718,1.285472,1.342392,1.322733,1.302577,...,1.196017,CBPD0265,6.138388,1.0,-0.108923,-0.007488,1.692037,sub-CBPD0265,-0.272211,1.286317