In [2]:
import pandas as pd
import numpy as np

In [5]:
cbpd = pd.read_csv("../derivatives/CBPD_data_DMD_2023.11.14.csv")
nwbd = pd.read_csv("../derivatives/NWBD_BrannonBehaviorLogs_11.5.2019.csv")

In [6]:
cbpd['parent_edu'] = [np.nanmean([cbpd['parent1_edu'][i], cbpd['parent2_edu'][i]]) for i in np.arange(cbpd.shape[0])]

<ipython-input-6-87c3df96cd06>:1: RuntimeWarning: Mean of empty slice
  cbpd['parent_edu'] = [np.nanmean([cbpd['parent1_edu'][i], cbpd['parent2_edu'][i]]) for i in np.arange(cbpd.shape[0])]

In [7]:
timepoint1 = [i for i in np.arange(cbpd.shape[0]) if '_' not in cbpd.record_id.values[i]]
timepoint2 = [i for i in np.arange(cbpd.shape[0]) if '_2' in cbpd.record_id.values[i]]
timepoint3 = [i for i in np.arange(cbpd.shape[0]) if '_3' in cbpd.record_id.values[i]]

In [8]:
variables = ['record_id', 'age', 'male', 'parent_edu', 't1_rating_avg', 'income_rank', 'income_median', 'home_sum', 'epcuriosity_i', 'epcuriosity_d', 'apq_pos', 'fus_total']
columns = ['record_id', 'age_scan', 'male', 't1_rating_avg',  'parent_edu', 'income_rank', 'income_median', 'home_sum', 'epcuriosity_itype_sum', 'epcuriosity_dtype_sum', 'apq_pos_parent', 'fus_total_avg']

In [10]:
for i, timepoint in enumerate([timepoint1, timepoint2, timepoint3]):
    cbpd_t = cbpd.iloc[timepoint,:]
    cbpd_t = cbpd_t.loc[:, columns]
    #df_t['age_scan'] = (df_t.age_scan - df_t.age_scan.mean())/df_t.age_scan.std()
    #df_t.to_csv(f't{str(i+1)}.csv', index=None)

In [11]:
variables = ['record_id', 'age_scan', 'male', 't1_rating_avg']

,record_id,age_scan,male,t1_rating_avg,parent_edu,income_rank,income_median,home_sum,epcuriosity_itype_sum,epcuriosity_dtype_sum,apq_pos_parent,fus_total_avg
20,CBPD0018_3,6.740727,1,1.0,12.0,11.0,NaN,NaN,20.0,15.0,15.0,1.142857
28,CBPD0023_3,9.054373,0,1.5,12.0,NaN,NaN,25.0,20.0,16.0,15.0,1.142857
62,CBPD0048_3,9.213057,1,1.5,14.0,1.0,8500.0,25.0,16.0,14.0,15.0,NaN
95,CBPD0074_3,7.228074,1,2.5,20.0,NaN,NaN,27.0,18.0,14.0,15.0,1.136364
101,CBPD0077_3,9.018666,0,1.5,12.0,2.0,14000.0,21.0,18.0,16.0,14.0,2.090909
104,CBPD0078_3,9.018666,0,2.0,12.0,2.0,14000.0,20.0,20.0,18.0,14.0,2.090909
121,CBPD0091_3,6.831078,0,2.0,15.0,7.0,87500.0,28.0,14.0,11.0,14.0,2.333333
230,CBPD0184_3,NaN,0,1.0,18.0,10.0,NaN,NaN,NaN,NaN,NaN,1.272727
255,CBPD0205_3,NaN,1,NaN,13.0,1.0,8500.0,NaN,NaN,NaN,15.0,1.210526

In [12]:
nwbd

,Subject,DOB,Age_scan,Age_beh,male,DOScan,Scan_Mock First,"VideoPermissions (Level 1,2,3,4)",CheckSheet Form,Mock Scan,...,Letter word ID,ANS,Info (WPPSI),MR (WPPSI),PM (WPPSI),Ord Prod (Triangle),Ord Verif,RA,Session 2 Task Order,Session 2 Notes
0,NWBD1001,1/30/2014,5.025,5.311000,1.0,2/9/2019,1.0,NaN,A,1.0,...,NaN,0.0,1.0,1,1.0,1,1,CS,"Number ID, Order Production, Letter-Word, Info...","Order: Number ID, Order Production, Letter-Wor..."
1,NWBD1002,11/7/2011,7.256,7.547000,0.0,2/9/2019,1.0,NaN,A,1.0,...,NaN,1.0,1.0,1,1.0,1,1,CS,"Number ID, Symbolic Comparison, Letter Word ID...","Did ANS last, had to re-do order production be..."
2,NWBD1003,8/15/2014,4.522,4.586000,1.0,2/23/2019,1.0,"1,2",A,1.0,...,NaN,1.0,1.0,1,1.0,0,0,EZ,"Number ID, Symbolic Comparison, Letter Word ID...",quite tired initially; hard time paying attent...
3,NWBD1004,4/19/2012,6.900,6.942000,0.0,3/13/2019,1.0,"1,2,3",B,1.0,...,NaN,1.0,1.0,1,1.0,1,1,NaN,"Number ID, Symbolic Comparison, Letter Word ID...","took a snack break, a bathroom break, and had ..."
4,NWBD1005,11/28/2011,7.322,7.364000,0.0,3/24/2019,1.0,"1,2,3",A,1.0,...,NaN,1.0,1.0,1,1.0,1,1,EZ,"Verbal Quantity, Number ID, Symbolic Compariso...","generally fast, took a snack break, at verbal ..."
5,NWBD1006,10/17/2012,6.417,6.450000,1.0,3/17/2019,1.0,"1,2,3",B,1.0,...,NaN,1.0,1.0,1,1.0,0,0,CS,"Number ID, Letter Word ID, Symbolic Comparison...",Did letter word before symbolic comparison.
6,NWBD1007,10/31/2013,NaN,5.400000,1.0,NaN,1.0,"1, 2, 3",A,0.0,...,NaN,1.0,1.0,1,NaN,1,0,JH,"Number ID, Symbolic Comparison, Letter Word ID...",NaN
7,NWBD1008,12/8/2014,4.294,4.336000,1.0,3/24/2019,1.0,2,B,1.0,...,NaN,1.0,1.0,1,1.0,NaN,NaN,CS,"Verbal Quantity, Give-N, Keymath, Highest Coun...",Had a lot of energy. Frequently sang songs rel...
8,NWBD1009,9/3/2012,6.594,6.658000,0.0,4/7/2019,1.0,"1,2,3",A,1.0,...,NaN,1.0,1.0,1,1.0,1,1,CS,"Number ID, Symbolic Comparison, Letter Word ID...","During ANS, would sometimes use her nose to pr..."
9,NWBD1010,5/19/2014,4.883,4.947000,0.0,4/7/2019,0.0,"1,2,3",B,1.0,...,NaN,1.0,1.0,1,1.0,NaN,NaN,JC,"Number ID, Symbolic Comparison, Letter Word ID...",Notes from Nuwar: Next day when going to machi...
10,NWBD1011,2/26/2014,5.133,5.133000,1.0,NaN,1.0,"1,2",B,1.0,...,NaN,1.0,1.0,1,1.0,NaN,NaN,CS,"Verbal Quant, Symbolic Comparison, Order Produ...",No functioning computer.
11,NWBD1012,10/2/2013,5.533,5.572000,1.0,4/14/2019,0.0,"1,2,3",A,1.0,...,NaN,1.0,1.0,1,NaN,1,1,CS,"Number ID, Letter Word ID, Information WPPSI, ...","camera was switched out for another one, Camer..."
12,NWBD1013,1/17/2014,5.258,5.267000,0.0,4/20/2019,1.0,"1,2",A,1.0,...,NaN,1.0,1.0,1,1.0,1,1,CS,"Number ID, Symbolic Comparison, ANS Acuity, Le...",Did verbal quantity during session 2; Order of...
13,NWBD1014,11/30/2014,4.597,114.917000,0.0,7/5/2019,1.0,"1, 2, 3",B,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Number ID, Symbolic Comparison, Letter Word ID...",NaN
14,NWBD1015,6/3/2015,4.089,4.117000,0.0,7/5/2019,1.0,NaN,A,1.0,...,NaN,0.0,1.0,1,1.0,-,-,EK,"Number ID, Symbolic Comparison, Letter Word ID...","After completing Letter Word, child become non..."
15,NWBD1016,3/17/2015,4.397,4.625000,0.0,8/10/2019,1.0,3,B,1.0,...,NaN,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
16,NWBD1017,11/19/2014,4.689,4.719000,0.0,7/27/2019,1.0,"1,2",A,1.0,...,NaN,1.0,1.0,1,1.0,NaN,NaN,AJ,"Keymath, Highest Count, Number ID, Symbolic Co...",Don't think child completely understood symb c...
17,NWBD1018,1/27/2015,4.689,4.536000,0.0,10/5/2019,1.0,"1,2,3",B,1.0,...,1.0,0.0,1.0,1,1.0,0,0,NV,NaN,NaN
18,NWBD1019,6/12/2014,5.128,5.136000,0.0,7/28/2019,1.0,"1,2,3",A,1.0,...,NaN,1.0,1.0,1,1.0,1,1,EK,"Number ID, Symbolic Comparison, Letter Word ID...",Sym Comp: began clicking on other parts of the...
19,NWBD1020,5/29/2014,5.208,5.411000,1.0,8/14/2019,1.0,NaN,B,1.0,...,0.0,0.0,0.0,0,0.0,0,0,JC,"Number ID, tried to do Symbolic Comparison","very energetic, would not sit still for any ta..."
20,NWBD1021,6/12/2014,5.256,5.294000,1.0,9/14/2019,0.0,"1,2,3",A,1.0,...,NaN,1.0,1.0,1,1.0,1,1,EK (NA for session 3),"Session 2: Keymath, Highest Count, Number ID, ...",EK: I competed Give-N and Verbal Quantity. Bo...
21,NWBD1022,5/2/2015,4.286,115.339000,0.0,8/15/2019,1.0,"1,2",B,1.0,...,1.0,1.0,1.0,1,1.0,0,0,AJ,NaN,Very distracted and may not have taken the tas...
22,NWBD1023,8/4/2015,115.594,115.594000,1.0,NaN,1.0,NaN,A,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(No tasks completed),NaN
23,NWBD1024,2/15/2014,5.678,5.600000,1.0,10/19/2019,1.0,"1,2",B,1.0,...,1.0,1.0,1.0,1,1.0,1,1,FB,Missing session 2 sheets!,Child was a bit distracted. It was difficult ...
24,NWBD1025,4/24/2012,7.389,7.389000,1.0,9/14/2019,1.0,NaN,A,1.0,...,NaN,1.0,1.0,1,1.0,1,1,AJ,"Number ID, Symbolic Comparison, Letter Word ID...",Started to get tired towards end
25,NWBD1026,9/7/2013,113.686,113.686000,0.0,NaN,NaN,NaN,B,NaN,...,NaN,1.0,1.0,1,1.0,1,0,JC/NA,NaN,"took a few breaks, child got tired and wanted ..."
26,NWBD1027,NaN,,0.000000,NaN,NaN,NaN,NaN,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NWBD1028,12/18/2014,4.797,4.758000,1.0,10/5/2019,0.0,"1,2,3",B,1.0,...,NaN,1.0,1.0,1,1.0,0,0,EK,NaN,Child was calm and relatively focused.
28,NWBD1029,12/13/2013,5.792,113.953000,1.0,9/28/2019,1.0,"1,2,3",B,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NWBD1030,2/19/2014,5.614,5.689000,1.0,9/30/2019,1.0,"1,2,3",A,1.0,...,1.0,1.0,1.0,1,1.0,1,1,NB,correct order,Touch screen not working on 65 so we switched ...
30,NWBD1031,2/16/2015,4.617,115.128000,0.0,9/28/2019,1.0,unfilled,B,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NWBD1032,1/27/2013,6.669,113.075000,1.0,9/28/2019,0.0,unfilled,A,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NWBD1033,1/24/2015,4.683,115.067000,1.0,9/30/2019,1.0,"1,2",A,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NWBD1034,5/26/2015,4.397,4.344000,0.0,10/19/2019,1.0,"1,2",B,1.0,...,1.0,1.0,1.0,1,1.0,0,0,NB,correct order,He's very sweet but he gets tired easily. Only...
34,NWBD1035,NaN,0.000,0.000000,NaN,NaN,NaN,NaN,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NWBD1036,NaN,0.000,0.000000,NaN,NaN,NaN,NaN,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NWBD1037 Also 97 ordering,NaN,119.764,0.000000,0.0,10/5/2019,0.0,NaN,A,1.0,...,NaN,0.0,0.0,0,0.0,0,0,NaN,Completed Ordering before Session 2: Number ID...,NaN
37,NWBD1038,12/3/2014,4.842,4.900000,1.0,10/6/2019,1.0,"1,2,3",B,1.0,...,1.0,1.0,1.0,1,1.0,0,0,NB,"Letterword, number ID, Sym comp, ANS, info, m...",didn't finish ANS
38,NWBD1039,10/27/2014,114.825,4.942000,0.0,NaN,0.0,unfilled,A,1.0,...,1.0,1.0,1.0,1,1.0,1,1,NB/EK,"Mock scan, Give-N, Verbal Quant, Keymath, High...",We did things out of order because she kept ge...
39,NWBD1040,NaN,0.000,0.000000,NaN,NaN,NaN,NaN,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NWBD1041,10/3/2013,6.008,6.081000,0.0,10/6/2019,1.0,"1, 2",A,1.0,...,1.0,1.0,1.0,1,1.0,1,1,EH,"Number ID, Symbolic Comparison, Letterword, AN...","For order production, child accidentally press..."
41,NWBD1042,5/27/2015,4.358,115.408000,1.0,10/6/2019,0.0,2,B,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NWBD1043,NaN,0.000,0.000000,NaN,NaN,NaN,NaN,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NWBD1044,1/23/2015,4.700,115.064000,1.0,10/5/2019,1.0,unfilled,B,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NWBD1045,7/10/2015,4.278,4.311000,1.0,10/20/2019,1.0,"1,2,3",B,1.0,...,1.0,1.0,1.0,1,1.0,0,0,NB,Correct order,NaN
45,NWBD1046,NaN,0.000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NWBD1047,NaN,0.000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NWBD1048,11/12/2012,6.939,6.956000,0.0,10/20/2019,1.0,2,B,1.0,...,1.0,1.0,1.0,1,1.0,1,1,CS/NA,NaN,"So sweet, and tried to keep things entertainin..."
48,NWBD1049,10/28/2014,4.978,4.978000,0.0,10/20/2019,0.0,2,A,1.0,...,1.0,1.0,1.0,1,1.0,0,0,EK,NaN,"ANS: was interrupted for one of the trials, wa..."
49,NWBD1050,6/12/2015,115.450,4.350000,0.0,NaN,1.0,"1,2,3",B,1.0,...,NaN,0.0,0.0,did not complete,0.0,1,1,JC,NaN,NaN
50,NWBD1051,1/3/2013,6.797,6.817000,0.0,10/20/2019,1.0,1,A,1.0,...,1.0,1.0,1.0,1,1.0,1,1,JP,NaN,"Touch wasn't working for tasks, so used click ..."
51,NWBD1052,9/26/2014,5.103,5.067000,0.0,11/3/2019,0.0,"1,2",B,1.0,...,0.0,0.0,1.0,1,0.0,0,0,EH for first half NB for Sym Comp,NaN,"Num ID: confused about ""1"" with a line at the ..."
52,NWBD1053,1/2/2015,4.836,115.006000,1.0,11/3/2019,1.0,"1,2,3",A,1.0,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NB for two tasks,NaN,NaN
53,NWBD1054,10/11/2012,7.061,112.781000,1.0,11/3/2019,1.0,"1,2,3",B,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NWBD1055,NaN,0.000,0.000000,NaN,NaN,NaN,NaN,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NWBD1056,5/15/2014,5.466666667,5.466667,1.0,11/3/2019,1.0,"1,2",B,1.0,...,0.0,0.0,0.0,0,0.0,0,0,EH,NaN,NaN
56,NWBD1057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NWBD1058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NWBD 1059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
nwbd.columns

Index(['Subject', 'DOB', 'Age_scan', 'Age_beh', 'male', 'DOScan',
       'Scan_Mock First', 'VideoPermissions (Level 1,2,3,4)',
       'CheckSheet Form', 'Mock Scan', 'Mock_RA', 'GiveN', 'Mapping',
       'Numeration', 'Count/HH', 'Behavioral_RA', 'Session 1 Task Order',
       'Session 1 Notes', 'DOBehavioral', 'NumID', 'SymComp', 'Letter word ID',
       'ANS', 'Info (WPPSI)', 'MR (WPPSI)', 'PM (WPPSI)',
       'Ord Prod (Triangle)', 'Ord Verif', 'RA', 'Session 2 Task Order',
       'Session 2 Notes'],
      dtype='object')